---
title: "Introduction"
format: html
date-modified: last-modified
date-format: long
date: 2024-01-01
bibliography: resources/references.bib
#https://emojidb.org/quarto-emojis for emojis copypaste
---

**Here** is *where* you will write an abstract about the course. This is an example of the use of citations [@creative_commons_2022] and [@Garcia2020].

:::{.callout-note title="Course Overview"}
    
- 📖 **Syllabus:** 

  1. First item  
  2. Second item  

- **Total Time Estimation:** X hours  
[comment]: # (No Property in Bioschema)

- :file_folder: **Supporting Materials:**  
[comment]: # (Property in Bioschema: mentions)

- :man_technologist: **Target Audience:** PhD, MsC, etc.
[comment]: # (Property in Bioschema: audience)

- :woman_student: **Level:** Beginner/Intermediate/Advanced
[comment]: # (Property in Bioschema: educationalLevel)

- :lock: **License:** [Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) license.](https://creativecommons.org/licenses/by-sa/4.0/legalcode)
[comment]: # (Property in Biochema: licence)

- :coin: **Funding:** This project was funded by the Novo Nordisk Fonden (NNF20OC0063268).
[comment]: # (Funding by NNF and others)
:::

!!! warning "Course Requirements"
    - First requirement
    - Second requirement

This is where you should write a longer introduction to the course.

!!! info "Goals"
    By the end of this workshop, you should be able to:

    - Goal 1
    - Goal 2
    -   

### Acknowledgements

- First acknowledgement

### Print a table

```{r}
#| echo: false
library(gt)
# Load the data from CSV
data <- read.csv("resources/samplesheet.csv")

# Print the data as a table
data %>% gt()
```























<script type="application/ld+json" >
    {
      "@context": "https://schema.org",
      "@id": "# Put here the course webpage (https://hds-sandbox.github.io/bulk_RNAseq_course/)",
      "@type": "LearningResource",
      "dct:conformsTo": "https://bioschemas.org/profiles/TrainingMaterial/1.0-RELEASE",
      "description": "# Course description",
      "keywords": [
        "# Keyword1, Keyword2, etc"
      ],
      "learningResourceType": [
        "e-learning"
      ],
      "license": [
        {
          "@id": "# Link to license webpage (https://creativecommons.org/licenses/by-sa/4.0/)",
          "@type": "CreativeWork"
        }
      ],
      "mentions": [
        {
          "@id": "# Link to DOI or zenodo materials (10.5281/zenodo.7660225)",
          "@type": "Thing"
        },
        {
          "@id": "#Another link to DOI or zenodo materials (10.5281/zenodo.7565997)",
          "@type": "Thing"
        }
      ],
      "name": "# Name of the workshop (Introduction to bulk RNAseq analysis workshop)",
      "educationalLevel": "# One of: Beginner, Intermediate or Advanced",
      "audience": "# PhD, postdocs, MSc, etc"
    }
    </script >