channels:
  - conda-forge
  - bioconda
  - r
  - anaconda
  - plotly
  - grst
  - gwforg
  - genomedk
dependencies:
  - bioconda::regenie
  - conda-forge::jupyterlab
  - conda-forge::gcc_linux-64
  - bioconda::bwa
  - bioconda::bcftools[version='1.16']
  - bioconda::samtools[version='1.6']
  - conda-forge::ca-certificates
  - conda-forge::openssl
  - conda-forge::r-base>=4.0.0
  - conda-forge::r-ggplot2
  - conda-forge::r-dplyr
  - conda-forge::r-tidyverse
  - conda-forge::r-irkernel
  - conda-forge::certifi
  - conda-forge::ipykernel
  - conda-forge::ipywidgets
  - bioconda::minimap2
  - conda-forge::pandas
  - conda-forge::r-vcfr
  - bioconda::vcftools
  - conda-forge::cxx-compiler
  - bioconda::snakemake
  - conda-forge::nodejs
  - conda-forge::r-tidyr
  - bioconda::bioconductor-snprelate
  - bioconda::psmc
  - conda-forge::ghostscript
  - conda-forge::gnuplot
  - conda-forge::bash_kernel
  - bioconda::plink
  - bioconda::plink2
  - bioconda::nextflow
  - gwforg::gwf
  - conda-forge::r-data.table
  - conda-forge::r-gridextra
  - conda-forge::r-cowplot
  - conda-forge::numpy
  - conda-forge::networkx
  - conda-forge::dash
  - conda-forge::dash-bootstrap-components
  - conda-forge::dash-core-components
  - conda-forge::dash-html-components
  - conda-forge::matplotlib
  - conda-forge::r-qqman
  - bioconda::gcta
  - bioconda::admixture
  - conda-forge::conda-pack
  - bioconda::bioconductor-deseq2
  - bioconda::bioconductor-edger
  - conda-forge::gsl
  - conda-forge::scanpy
  - bioconda::harmonypy
  - bioconda::bbknn
  - conda-forge::python-igraph
  - conda-forge::leidenalg
  - conda-forge::python-annoy
  - conda-forge::multicore-tsne
  - conda-forge::pytables
  - conda-forge::plotly
  - conda-forge::nbformat
  - bioconda::star==2.7.10a
  - conda-forge::scikit-allel
  - bioconda::fastqc
  - bioconda::multiqc
  - bioconda::qualimap
  - bioconda::minimap2
  - conda-forge::r-formattable
  - conda-forge::r-venndiagram
  - conda-forge::r-pheatmap
  - conda-forge::r-mixomics
  - bioconda::gffread
  - conda-forge::cython
  - conda-forge::scikit-image
  - conda-forge::imageio
  - conda-forge::tifffile
  - conda-forge::charset-normalizer
  - conda-forge::colorama
  - conda-forge::idna
  - conda-forge::pycparser
  - conda-forge::pyopenssl
  - conda-forge::pip
  - icu
  - libgomp
  - libblas
  - liblapack
  - readline
  - rpy2
  - conda-forge::jupyter-lsp
  - conda-forge::jupyter-lsp-r
  - conda-forge::jupyter-lsp-python
  - conda-forge::jupyter-lsp-latex
  - ldak6
  - pip
  - pip:
    - scvelo
    - pydeseq2
    - batchglm
    - robustbase==0.2.8
    - scrublet==0.2.3
    - sparse
    - requests
    - six
    - tqdm
    - urllib3
    - wheel 
    - jupyter-resource-usage
    - autopep8
    - yapf
    - isort 
    - black
    - jupyterlab-code-formatter
    - jupyterlab-git
    - jupyter_bokeh
    - jupyterquiz
    - jupyterlab-quarto
    - nbconvert[webpdf]
    - doubletdetection
    - eir-dl