on: 
  push:
    branches: 
      - main
    paths:
      - 'Webpage/**'
    workflow_dispatch:

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install libcurl on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

# If you do not need any R package for notebooks or R Markdown documents, you can skip the following two steps by removing them.
# For this template you have a lock file with some packages installed to be able to print tables in markdown and compile the R markdown page example

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2

# This part publishes the website to the gh-pages branch
# but looks specifically at Webpage folder to find the _quarto.yml file
# default would be looking at the root of the repository

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: Webpage